name: isye-6739-project
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.3
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cycler=0.11.0
  - dbus=1.13.6
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.70.1
  - glib-tools=2.70.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=68.2
  - jbig=2.1
  - jpeg=9d
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.1
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.5
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mysql-common=8.0.27
  - mysql-libs=8.0.27
  - ncurses=6.2
  - nspr=4.32
  - nss=3.72
  - numpy=1.21.4
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.3.1
  - pthread-stubs=0.4
  - pyparsing=3.0.6
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - qt=5.12.9
  - readline=8.1
  - setuptools=59.4.0
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - tornado=6.1
  - tzdata=2021e
  - wheel=0.37.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - bashplotlib==0.6.5
